# DevSecOps Pipeline Configuration
# This file contains all configurable parameters for the security pipeline

security:
  # Static Application Security Testing thresholds
  sast:
    threshold: 5
    level: "low"
    tools:
      - bandit
      - semgrep
      - sonarqube
  
  # Software Composition Analysis thresholds
  sca:
    threshold: 10
    tools:
      - safety
      - dependency-check
      - snyk
  
  # Container security thresholds
  container:
    threshold: 3
    tools:
      - trivy
      - lynis
      - clair
  
  # Dynamic Application Security Testing thresholds
  dast:
    threshold: 5
    tools:
      - nikto
      - zap
      - burp
  
  # Secret scanning configuration
  secrets:
    tools:
      - trufflehog
      - git-secrets
      - detect-secrets

aws:
  region: "eu-west-2"
  instance_type: "t3.medium"
  cleanup: true
  spot_instances: true
  vpc:
    cidr: "10.0.0.0/16"
    public_subnet: "10.0.1.0/24"
    private_subnet: "10.0.2.0/24"

notifications:
  email: "security-team@company.com"
  slack: "#security-alerts"
  teams: "#security-channel"
  webhook: "https://hooks.slack.com/services/YOUR/WEBHOOK/URL"

monitoring:
  prometheus: true
  grafana: true
  elasticsearch: true
  kibana: true

artifacts:
  retention_days: 30
  storage:
    type: "s3"
    bucket: "security-reports"
    region: "eu-west-2"

compliance:
  frameworks:
    - "OWASP Top 10"
    - "NIST Cybersecurity Framework"
    - "ISO 27001"
  reporting:
    format: ["html", "json", "pdf"]
    executive_summary: true
    detailed_reports: true 